### ISSUE TITLE
How to Use

### ISSUE THREAD

**Issue by kortin99** [odestry/tailwindcss-rem-to-px#1]
Hi👋 
Firstly, thanks for your work. 

As a newcomer to Tailwind CSS, I'm look forward a lib to help me convert rem units to px units, but I am unsure about how to integrate into my project and I haven't found relevant information in the current documentation.

Could you have some description about how to use it?

**Comment by blanklob** [comment]
Hey @kortin99 I just added docs [here](https://github.com/odestry/tailwindcss-rem-to-px?tab=readme-ov-file#usage) feel free to ask if you have other questions, thanks!
